#!/usr/bin/env python3
"""
Script to create a sample DOCX template with Jinja2 placeholders.
Run this once to generate the initial template file.
"""

from pathlib import Path
from docx import Document
from docx.shared import Inches, Pt
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.table import WD_TABLE_ALIGNMENT


def create_sample_template():
    """Create a sample client report template with Jinja2 placeholders."""
    doc = Document()
    
    # Title
    title = doc.add_heading("Client Report", level=0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    
    # Client info section
    doc.add_heading("{{ client_name }}", level=1)
    doc.add_paragraph("Report Date: {{ report_date }}")
    doc.add_paragraph("Report Period: {{ report_period }}")
    doc.add_paragraph("Prepared By: {{ prepared_by }}")
    
    doc.add_paragraph()  # Spacer
    
    # Executive Summary
    doc.add_heading("Executive Summary", level=2)
    doc.add_paragraph("{{ executive_summary }}")
    
    doc.add_paragraph()  # Spacer
    
    # Key Metrics Table
    doc.add_heading("Key Performance Metrics", level=2)
    table = doc.add_table(rows=1, cols=4)
    table.style = "Table Grid"
    table.alignment = WD_TABLE_ALIGNMENT.CENTER
    
    # Header row
    header_cells = table.rows[0].cells
    header_cells[0].text = "Metric"
    header_cells[1].text = "Value"
    header_cells[2].text = "Change"
    header_cells[3].text = "Status"
    
    # Make headers bold
    for cell in header_cells:
        for paragraph in cell.paragraphs:
            for run in paragraph.runs:
                run.bold = True
    
    # Template row for metrics (Jinja2 loop)
    doc.add_paragraph("{%tr for metric in metrics %}")
    metric_table = doc.add_table(rows=1, cols=4)
    metric_table.style = "Table Grid"
    cells = metric_table.rows[0].cells
    cells[0].text = "{{ metric.name }}"
    cells[1].text = "{{ metric.value }}"
    cells[2].text = "{{ metric.change }}"
    cells[3].text = "{{ metric.status }}"
    doc.add_paragraph("{%tr endfor %}")
    
    # Alternative simple loop approach (more reliable)
    doc.add_paragraph()
    doc.add_paragraph("{% for metric in metrics %}")
    doc.add_paragraph("• {{ metric.name }}: {{ metric.value }} ({{ metric.change }})")
    doc.add_paragraph("{% endfor %}")
    
    doc.add_paragraph()  # Spacer
    
    # Highlights Section
    doc.add_heading("Key Highlights", level=2)
    doc.add_paragraph("{% for highlight in highlights %}")
    doc.add_paragraph("• {{ highlight }}")
    doc.add_paragraph("{% endfor %}")
    
    doc.add_paragraph()  # Spacer
    
    # Recommendations Section  
    doc.add_heading("Recommendations", level=2)
    doc.add_paragraph("{% for rec in recommendations %}")
    doc.add_paragraph("[{{ rec.priority }}] {{ rec.title }}")
    doc.add_paragraph("{{ rec.description }}")
    doc.add_paragraph()
    doc.add_paragraph("{% endfor %}")
    
    doc.add_paragraph()  # Spacer
    
    # Contact Section
    doc.add_heading("Contact Information", level=2)
    doc.add_paragraph("{{ contact.name }}")
    doc.add_paragraph("{{ contact.title }}")
    doc.add_paragraph("Email: {{ contact.email }}")
    doc.add_paragraph("Phone: {{ contact.phone }}")
    
    # Footer
    doc.add_paragraph()
    footer = doc.add_paragraph("Generated by Client Report Engine")
    footer.alignment = WD_ALIGN_PARAGRAPH.CENTER
    
    # Save template
    template_dir = Path(__file__).resolve().parents[1] / "reports" / "templates"
    template_dir.mkdir(parents=True, exist_ok=True)
    template_path = template_dir / "sample_report.docx"
    doc.save(template_path)
    
    print(f"Template created at: {template_path}")
    return template_path


if __name__ == "__main__":
    create_sample_template()

